cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-template-role
  namespace: argo-events
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtemplates"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-template-rolebinding
  namespace: argo-events
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-events
roleRef:
  kind: Role
  name: workflow-template-role
  apiGroup: rbac.authorization.k8s.io
EOF
