# ####################### without analysis we will run this yaml file ####################
# apiVersion: argoproj.io/v1alpha1    # এটি নির্দেশ করে যে আমরা Argo Rollouts এর একটি কাস্টম রিসোর্স তৈরি করছি, যা Argo Rollouts দ্বারা সংজ্ঞায়িত করা হয়েছে।
# kind: Rollout       # এই রিসোর্সের ধরণ হল Rollout, যা একটি কাস্টম রিসোর্স যা Argo Rollouts দ্বারা ব্যবহৃত হয় ক্যানারি বা ব্লু-গ্রিন ডিপ্লয়মেন্ট কৌশলগুলি পরিচালনা করতে।
# metadata:       # এই অংশটি রিসোর্সের মেটাডেটা সংজ্ঞায়িত করে, যেমন নাম, লেবেল ইত্যাদি।
#   name: rollouts-setweight    # রোলআউটের নাম, যা ইউনিক হতে হবে ক্লাস্টারে।
# spec:                         # এই অংশটি রোলআউটের স্পেসিফিকেশন সংজ্ঞায়িত করে, যা ডিপ্লয়মেন্ট কৌশল, রেপ্লিকা সংখ্যা, পড টেমপ্লেট ইত্যাদি নির্ধারণ করে।
#   replicas: 5                 # ডিপ্লয়মেন্টে মোট 5 রেপ্লিকা থাকবে, যা নির্দেশ করে যে 5টি পড চলমান থাকবে।
#   selector:                   # Rollout কোন Pod গুলোকে manage করবে তা label দিয়ে নির্ধারণ করে/এই অংশটি পড সিলেক্টর সংজ্ঞায়িত করে, যা নির্ধারণ করে কোন পডগুলি এই রোলআউটের অংশ হবে।
#     matchLabels:        		  # এই label-এর সাথে মিল থাকা Pod গুলো Rollout-এর অধীনে থাকবে
#       app: rollouts-setweight       # এই লেবেল সিলেক্টরটি নির্ধারণ করে যে যেসব পডে "app: rollouts-setweight" লেবেল আছে, তারা এই রোলআউটের অংশ হবে।
#   strategy:                   	# ডিপ্লয়মেন্ট কৌশল সংজ্ঞায়িত করে, যা এই ক্ষেত্রে ক্যানারি ডিপ্লয়মেন্ট কৌশল।
#     canary:       			# ক্যানারি ডিপ্লয়মেন্ট কৌশল সংজ্ঞায়িত করে, যা ধাপে ধাপে নতুন সংস্করণে ট্র্যাফিক স্থানান্তর করে।
#       steps:      			# ক্যানারি ডিপ্লয়মেন্টের ধাপগুলি সংজ্ঞায়িত করে, যা নতুন সংস্করণে ট্র্যাফিক স্থানান্তর করার জন্য নির্দিষ্ট করা হয়।
#       - setWeight: 20   		# প্রথম ধাপে, নতুন সংস্করণে 20% ট্র্যাফিক স্থানান্তর করা হবে।
#       - pause: {}     			# দ্বিতীয় ধাপে, একটি বিরতি থাকবে যা ডিফল্টভাবে 30 সেকেন্ডের জন্য স্থায়ী হবে, যা নতুন সংস্করণে ট্র্যাফিক স্থানান্তরের পরে পর্যবেক্ষণ করার জন্য ব্যবহৃত হয়।
#       - setWeight: 40   		# তৃতীয় ধাপে, নতুন সংস্করণে 40% ট্র্যাফিক স্থানান্তর করা হবে।
#       - pause: {duration: 10s}    # তৃতীয় ধাপের পরে, একটি বিরতি থাকবে যা 10 সেকেন্ডের জন্য স্থায়ী হবে, যা নতুন সংস্করণে ট্র্যাফিক স্থানান্তরের পরে পর্যবেক্ষণ করার জন্য ব্যবহৃত হয়।
#       - setWeight: 60   		# চতুর্থ ধাপে, নতুন সংস্করণে 60% ট্র্যাফিক স্থানান্তর করা হবে।  
#       - pause: {duration: 20s}    # চতুর্থ ধাপের পরে, একটি বিরতি থাকবে যা 20 সেকেন্ডের জন্য স্থায়ী হবে, যা নতুন সংস্করণে ট্র্যাফিক স্থানান্তরের পরে পর্যবেক্ষণ করার জন্য ব্যবহৃত হয়।
#       - setWeight: 80           	# পঞ্চম ধাপে, নতুন সংস্করণে 80% ট্র্যাফিক স্থানান্তর করা হবে।
#       - pause: {duration: 1m}   	# পঞ্চম ধাপের পরে, একটি বিরতি থাকবে যা 1 মিনিটের জন্য স্থায়ী হবে, যা নতুন সংস্করণে ট্র্যাফিক স্থানান্তরের পরে পর্যবেক্ষণ করার জন্য ব্যবহৃত হয়।
#   template:               		# এই অংশটি পড টেমপ্লেট সংজ্ঞায়িত করে, যা নির্ধারণ করে যে রোলআউটের পডগুলি কেমন হবে।
#     metadata:               		# এই অংশটি পডের মেটাডেটা সংজ্ঞায়িত করে, যেমন লেবেল ইত্যাদি।
#       labels:               		# এই অংশটি লেবেল সংজ্ঞায়িত করে, যা নির্ধারণ করে যে এই পডগুলিতে কোন লেবেল থাকবে।
#         app: rollouts-setweight   # এই লেবেলটি নির্ধারণ করে যে এই পডগুলিতে "app: rollouts-setweight" লেবেল থাকবে, যা রোলআউটের সিলেক্টর দ্বারা ব্যবহৃত হবে।
#     spec:                         # এই অংশটি পডের স্পেসিফিকেশন সংজ্ঞায়িত করে, যা নির্ধারণ করে যে পডগুলি কেমন হবে, যেমন কোন কন্টেইনার থাকবে, কোন ইমেজ ব্যবহার করা হবে, কোন পোর্ট ব্যবহার করা হবে ইত্যাদি।
#       containers:                 # এই অংশটি কন্টেইনার সংজ্ঞায়িত করে, যা নির্ধারণ করে যে পডগুলিতে কোন কন্টেইনার থাকবে, কোন ইমেজ ব্যবহার করা হবে, কোন পোর্ট ব্যবহার করা হবে ইত্যাদি।
#       - name: rollouts-setweight  # এই অংশটি কন্টেইনারের নাম সংজ্ঞায়িত করে, যা ইউনিক হতে হবে পডের মধ্যে।
#         image: nuruzzaman24x/canary # এই অংশটি কন্টেইনার ইমেজ সংজ্ঞায়িত করে, যা নির্ধারণ করে যে পডগুলিতে কোন ইমেজ ব্যবহার করা হবে। এখানে "nuruzzaman24x/canary" ইমেজ ব্যবহার করা হচ্ছে, যা একটি ক্যানারি ডিপ্লয়মেন্টের জন্য তৈরি করা হয়েছে।
#         imagePullPolicy: Always     # এই অংশটি ইমেজ পুল পলিসি সংজ্ঞায়িত করে, যা নির্ধারণ করে যে কিভাবে কন্টেইনার ইমেজ পুল করা হবে। "Always" মানটি নির্দেশ করে যে কন্টেইনার ইমেজ প্রতিবার পড তৈরি বা রিস্টার্ট করার সময় পুল করা হবে, যা ডেভেলপমেন্ট বা টেস্টিং পরিবেশে সাধারণত ব্যবহৃত হয়।
#         env:                      # এই অংশটি পরিবেশ ভেরিয়েবল সংজ্ঞায়িত করে, যা নির্ধারণ করে যে কন্টেইনারে কোন পরিবেশ ভেরিয়েবল থাকবে।                
#         - name: html_name         # এই অংশটি পরিবেশ ভেরিয়েবলের নাম সংজ্ঞায়িত করে, যা "html_name" হবে।
#           value: "app-v1.html"     # এই অংশটি পরিবেশ ভেরিয়েবলের মান সংজ্ঞায়িত করে, যা "app-v1.html" হবে। এটি নির্দেশ করে যে কন্টেইনারে "html_name" পরিবেশ ভেরিয়েবল থাকবে যার মান "app-v1.html" হবে, যা সম্ভবত অ্যাপ্লিকেশনটির HTML ফাইলের নাম নির্দেশ করে।
#         ports:                     # এই অংশটি পোর্ট সংজ্ঞায়িত করে, যা নির্ধারণ করে যে কন্টেইনারে কোন পোর্ট ব্যবহার করা হবে।
#         - containerPort: 5000     # এই অংশটি কন্টেইনার পোর্ট সংজ্ঞায়িত করে, যা 5000 হবে। এটি নির্দেশ করে যে কন্টেইনারে 5000 পোর্ট ব্যবহার করা হবে, যা সম্ভবত অ্যাপ্লিকেশনটির সার্ভিস পোর্ট হবে।#  
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rollouts-setweight
# spec:
#   ports:
#   - port: 5000
#     protocol: TCP
#     targetPort: 5000
#   selector:
#     app: rollouts-setweight




############## Argo Rollouts — AnalysisTemplate=ক্যানারি ডিপ্লয়মেন্টের সময় নতুন ভার্সন ঠিকঠাক কাজ করছে কিনা সেটা চেক করার নিয়ম ##########

apiVersion: argoproj.io/v1alpha1      # Kubernetes কে বলছি — এটা Argo Rollouts এর একটা বিশেষ রিসোর্স যেমন বলছ "এটা সাধারণ Kubernetes না, Argo Rollouts এর জিনিস"
kind: AnalysisTemplate                # এই রিসোর্সের ধরণ হল AnalysisTemplate, যা একটি কাস্টম রিসোর্স যা Argo Rollouts দ্বারা ব্যবহৃত হয় ক্যানারি ডিপ্লয়মেন্টের সময় বিশ্লেষণ করার জন্য।
metadata:                 # এই অংশটি রিসোর্সের মেটাডেটা সংজ্ঞায়িত করে, যেমন নাম, লেবেল ইত্যাদি।
  name: success-rate      # এই টেমপ্লেটের নাম "success-rate" — পরে Rollout ফাইল থেকে এই নামে ডাকা হবে
spec:                     
  metrics:            # আমরা "সফলতার হার" মেপে দেখব — নতুন ভার্সনের রিকোয়েস্টগুলো সফল হচ্ছে কিনা
  - name: success-rate    # এই অংশটি মেট্রিক্সের নাম সংজ্ঞায়িত করে, যা "success-rate" হবে, যা নির্দেশ করে যে এই মেট্রিক্সটি সফলতার হার পরিমাপ করবে।
    successCondition: result == "true"      # যদি API থেকে true আসে, তাহলে পরীক্ষা পাস API বলল "সব ঠিক আছে" → ডিপ্লয়মেন্ট এগিয়ে যাবে
    provider:         # একটা বাইরের URL এ HTTP কল করে ফলাফল জানব
      web:            # এই অংশটি ওয়েব হুক প্রদানকারী সংজ্ঞায়িত করে, যা নির্ধারণ করে যে এই মেট্রিক্সটি একটি ওয়েব হুক কলের মাধ্যমে পরিমাপ করা হবে, যা ক্যানারি ডিপ্লয়মেন্টের সময় সফলতার হার পরিমাপ করবে।
        method: POST    # POST পদ্ধতিতে ডেটা পাঠিয়ে কল করব GET = শুধু চাওয়া, POST = ডেটাসহ চাওয়া
        url: "http://172.17.0.232:5001/measure_success_rate"    # এই ঠিকানায় কল যাবে — যেখানে সফলতার হার মাপা হবে
        # url: "http://{{args.service_address}}:{{args.service_port}}/measure_success_rate"
        timeoutSeconds: 60      # ৬০ সেকেন্ডের মধ্যে জবাব না এলে, কলটা বাতিল হবে
        headers:        # সার্ভারকে বলছি — আমি JSON ফরম্যাটে ডেটা পাঠাচ্ছি
        - key: Content-Type
          value: application/json
        jsonBody:
          url: "http://rollouts-setweight.demo:32577"   # যে সার্ভিস চেক করব
        jsonPath: "{$.data.ok}"       # জবাব থেকে শুধু data.ok অংশটা নেব

---
apiVersion: argoproj.io/v1alpha1        # এটি নির্দেশ করে যে আমরা Argo Rollouts এর একটি কাস্টম রিসোর্স তৈরি করছি, যা Argo Rollouts দ্বারা সংজ্ঞায়িত করা হয়েছে।
kind: Rollout       # এই রিসোর্সের ধরণ হল Rollout, যা একটি কাস্টম রিসোর্স যা Argo Rollouts দ্বারা ব্যবহৃত হয় ক্যানারি বা ব্লু-গ্রিন ডিপ্লয়মেন্ট কৌশলগুলি পরিচালনা করতে।
metadata:           # এই অংশটি রিসোর্সের মেটাডেটা সংজ্ঞায়িত করে, যেমন নাম, লেবেল ইত্যাদি।
  name: rollouts-setweight      # রোলআউটের নাম, যা ইউনিক হতে হবে ক্লাস্টারে।
spec:              # এই অংশটি রোলআউটের স্পেসিফিকেশন সংজ্ঞায়িত করে, যা ডিপ্লয়মেন্ট কৌশল, রেপ্লিকা সংখ্যা, পড টেমপ্লেট ইত্যাদি নির্ধারণ করে।
  replicas: 5            # ডিপ্লয়মেন্টে মোট 5 রেপ্লিকা থাকবে, যা নির্দেশ করে যে 5টি পড চলমান থাকবে।
  selector:           # Rollout কোন Pod গুলোকে manage করবে তা label দিয়ে নির্ধারণ করে/এই অংশটি পড সিলেক্টর সংজ্ঞায়িত করে, যা নির্ধারণ করে কোন পডগুলি এই রোলআউটের অংশ হবে।
    matchLabels:      # এই অংশটি লেবেল সিলেক্টর সংজ্ঞায়িত করে, যা নির্ধারণ করে কোন পডগুলি এই রোলআউটের অংশ হবে।
      app: rollouts-setweight       # এই লেবেল সিলেক্টরটি নির্ধারণ করে যে যেসব পডে "app: rollouts-setweight" লেবেল আছে, তারা এই রোলআউটের অংশ হবে।

  strategy:       # ডিপ্লয়মেন্ট কৌশল সংজ্ঞায়িত করে, যা এই ক্ষেত্রে ক্যানারি ডিপ্লয়মেন্ট কৌশল।
    canary:         # ক্যানারি ডিপ্লয়মেন্ট কৌশল সংজ্ঞায়িত করে, যা ধাপে ধাপে নতুন সংস্করণে ট্র্যাফিক স্থানান্তর করে।
      analysis:       # এই অংশটি বিশ্লেষণ সংজ্ঞায়িত করে, যা ক্যানারি ডিপ্লয়মেন্টের সময় নির্দিষ্ট করা হয় এবং যা নির্ধারণ করে যে ক্যানারি ডিপ্লয়মেন্ট সফল হয়েছে কিনা।
          templates:    # এই অংশটি বিশ্লেষণ টেমপ্লেট সংজ্ঞায়িত করে, যা নির্ধারণ করে যে কোন বিশ্লেষণ টেমপ্লেট ব্যবহার করা হবে ক্যানারি ডিপ্লয়মেন্টের সময়।
          - templateName: success-rate        # এই অংশটি নির্ধারণ করে যে "success-rate" নামের বিশ্লেষণ টেমপ্লেট ব্যবহার করা হবে ক্যানারি ডিপ্লয়মেন্টের সময়, যা পূর্বে সংজ্ঞায়িত করা হয়েছে এবং একটি ওয়েব হুক কল করে সফলতার হার পরিমাপ করে।
      steps:        
      - setWeight: 20     # প্রথম ধাপে, নতুন সংস্করণে 20% ট্র্যাফিক স্থানান্তর করা হবে।
      - pause: {}                 # দ্বিতীয় ধাপে, একটি বিরতি থাকবে যা ডিফল্টভাবে 30 সেকেন্ডের জন্য স্থায়ী হবে, যা নতুন সংস্করণে ট্র্যাফিক স্থানান্তরের পরে পর্যবেক্ষণ করার জন্য ব্যবহৃত হয়।
  
      - setWeight: 40         # তৃতীয় ধাপে, নতুন সংস্করণে 40% ট্র্যাফিক স্থানান্তর করা হবে।
      - pause:                # তৃতীয় ধাপের পরে, একটি বিরতি থাকবে যা 10 সেকেন্ডের জন্য স্থায়ী হবে, যা নতুন সংস্করণে ট্র্যাফিক স্থানান্তরের পরে পর্যবেক্ষণ করার জন্য ব্যবহৃত হয়।
          duration: 10s       # চতুর্থ ধাপে, নতুন সংস্করণে 60% ট্র্যাফিক স্থানান্তর করা হবে।

      - setWeight: 60
      - pause:
          duration: 20s

      - setWeight: 80
      - pause:
          duration: 1m

      - setWeight: 100

  template:               # এই অংশটি পড টেমপ্লেট সংজ্ঞায়িত করে, যা নির্ধারণ করে যে রোলআউটের পডগুলি কেমন হবে।
    metadata:             # এই অংশটি পডের মেটাডেটা সংজ্ঞায়িত করে, যেমন লেবেল ইত্যাদি। 
      labels:             # এই অংশটি লেবেল সংজ্ঞায়িত করে, যা নির্ধারণ করে যে এই পডগুলিতে কোন লেবেল থাকবে।
        app: rollouts-setweight     # এই লেবেলটি নির্ধারণ করে যে এই পডগুলিতে "app: rollouts-setweight" লেবেল থাকবে, যা রোলআউটের সিলেক্টর দ্বারা ব্যবহৃত হবে।
    spec:               # এই অংশটি পডের স্পেসিফিকেশন সংজ্ঞায়িত করে, যা নির্ধারণ করে যে পডগুলি কেমন হবে, যেমন কোন কন্টেইনার থাকবে, কোন ইমেজ ব্যবহার করা হবে, কোন পোর্ট ব্যবহার করা হবে ইত্যাদি।
      containers:       # এই অংশটি কন্টেইনার সংজ্ঞায়িত করে, যা নির্ধারণ করে যে পডগুলিতে কোন কন্টেইনার থাকবে, কোন ইমেজ ব্যবহার করা হবে, কোন পোর্ট ব্যবহার করা হবে ইত্যাদি।
      - name: rollouts-setweight        # এই অংশটি কন্টেইনারের নাম সংজ্ঞায়িত করে, যা ইউনিক হতে হবে পডের মধ্যে।
        image: nuruzzaman24x/canary     # এই অংশটি কন্টেইনার ইমেজ সংজ্ঞায়িত করে, যা নির্ধারণ করে যে পডগুলিতে কোন ইমেজ ব্যবহার করা হবে। এখানে "nuruzzaman24x/canary" ইমেজ ব্যবহার করা হচ্ছে, যা একটি ক্যানারি ডিপ্লয়মেন্টের জন্য তৈরি করা হয়েছে।
        imagePullPolicy: Always         # এই অংশটি ইমেজ পুল পলিসি সংজ্ঞায়িত করে, যা নির্ধারণ করে যে কিভাবে কন্টেইনার ইমেজ পুল করা হবে। "Always" মানটি নির্দেশ করে যে কন্টেইনার ইমেজ প্রতিবার পড তৈরি বা রিস্টার্ট করার সময় পুল করা হবে, যা ডেভেলপমেন্ট বা টেস্টিং পরিবেশে সাধারণত ব্যবহৃত হয়।
        env:
        - name: html_name
          value: "app-v2.html"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-setweight
spec:
  selector:
    app: rollouts-setweight

  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP








# ############## Argo Rollouts — AnalysisTemplate=ক্যানারি ডিপ্লয়মেন্টের সময় নতুন ভার্সন ঠিকঠাক কাজ করছে কিনা সেটা চেক করার নিয়ম ##########

# apiVersion: argoproj.io/v1alpha1      # Kubernetes কে বলছি — এটা Argo Rollouts এর একটা বিশেষ রিসোর্স যেমন বলছ "এটা সাধারণ Kubernetes না, Argo Rollouts এর জিনিস"
# kind: AnalysisTemplate                # এই রিসোর্সের ধরণ হল AnalysisTemplate, যা একটি কাস্টম রিসোর্স যা Argo Rollouts দ্বারা ব্যবহৃত হয় ক্যানারি ডিপ্লয়মেন্টের সময় বিশ্লেষণ করার জন্য।
# metadata:                 # এই অংশটি রিসোর্সের মেটাডেটা সংজ্ঞায়িত করে, যেমন নাম, লেবেল ইত্যাদি।
#   name: success-rate      # এই টেমপ্লেটের নাম "success-rate" — পরে Rollout ফাইল থেকে এই নামে ডাকা হবে
# spec:                     
#   metrics:            # আমরা "সফলতার হার" মেপে দেখব — নতুন ভার্সনের রিকোয়েস্টগুলো সফল হচ্ছে কিনা
#   - name: success-rate    # এই অংশটি মেট্রিক্সের নাম সংজ্ঞায়িত করে, যা "success-rate" হবে, যা নির্দেশ করে যে এই মেট্রিক্সটি সফলতার হার পরিমাপ করবে।
#     successCondition: result == "true"      # যদি API থেকে true আসে, তাহলে পরীক্ষা পাস API বলল "সব ঠিক আছে" → ডিপ্লয়মেন্ট এগিয়ে যাবে
#     provider:         # একটা বাইরের URL এ HTTP কল করে ফলাফল জানব
#       web:            # এই অংশটি ওয়েব হুক প্রদানকারী সংজ্ঞায়িত করে, যা নির্ধারণ করে যে এই মেট্রিক্সটি একটি ওয়েব হুক কলের মাধ্যমে পরিমাপ করা হবে, যা ক্যানারি ডিপ্লয়মেন্টের সময় সফলতার হার পরিমাপ করবে।
#         method: POST    # POST পদ্ধতিতে ডেটা পাঠিয়ে কল করব GET = শুধু চাওয়া, POST = ডেটাসহ চাওয়া
#         url: "http://172.17.0.232:5001/measure_success_rate"    # এই ঠিকানায় কল যাবে — যেখানে সফলতার হার মাপা হবে
#         # url: "http://{{args.service_address}}:{{args.service_port}}/measure_success_rate"
#         timeoutSeconds: 60      # ৬০ সেকেন্ডের মধ্যে জবাব না এলে, কলটা বাতিল হবে
#         headers:        # সার্ভারকে বলছি — আমি JSON ফরম্যাটে ডেটা পাঠাচ্ছি
#         - key: Content-Type
#           value: application/json
#         jsonBody:
#           url: "http://rollouts-setweight.demo:32577"   # যে সার্ভিস চেক করব
#         jsonPath: "{$.data.ok}"       # জবাব থেকে শুধু data.ok অংশটা নেব

# ---
# apiVersion: argoproj.io/v1alpha1        # এটি নির্দেশ করে যে আমরা Argo Rollouts এর একটি কাস্টম রিসোর্স তৈরি করছি, যা Argo Rollouts দ্বারা সংজ্ঞায়িত করা হয়েছে।
# kind: Rollout       # এই রিসোর্সের ধরণ হল Rollout, যা একটি কাস্টম রিসোর্স যা Argo Rollouts দ্বারা ব্যবহৃত হয় ক্যানারি বা ব্লু-গ্রিন ডিপ্লয়মেন্ট কৌশলগুলি পরিচালনা করতে।
# metadata:           # এই অংশটি রিসোর্সের মেটাডেটা সংজ্ঞায়িত করে, যেমন নাম, লেবেল ইত্যাদি।
#   name: rollouts-setweight      # রোলআউটের নাম, যা ইউনিক হতে হবে ক্লাস্টারে।
# spec:              # এই অংশটি রোলআউটের স্পেসিফিকেশন সংজ্ঞায়িত করে, যা ডিপ্লয়মেন্ট কৌশল, রেপ্লিকা সংখ্যা, পড টেমপ্লেট ইত্যাদি নির্ধারণ করে।
#   replicas: 5            # ডিপ্লয়মেন্টে মোট 5 রেপ্লিকা থাকবে, যা নির্দেশ করে যে 5টি পড চলমান থাকবে।
#   selector:           # Rollout কোন Pod গুলোকে manage করবে তা label দিয়ে নির্ধারণ করে/এই অংশটি পড সিলেক্টর সংজ্ঞায়িত করে, যা নির্ধারণ করে কোন পডগুলি এই রোলআউটের অংশ হবে।
#     matchLabels:      # এই অংশটি লেবেল সিলেক্টর সংজ্ঞায়িত করে, যা নির্ধারণ করে কোন পডগুলি এই রোলআউটের অংশ হবে।
#       app: rollouts-setweight       # এই লেবেল সিলেক্টরটি নির্ধারণ করে যে যেসব পডে "app: rollouts-setweight" লেবেল আছে, তারা এই রোলআউটের অংশ হবে।

#   strategy:       # ডিপ্লয়মেন্ট কৌশল সংজ্ঞায়িত করে, যা এই ক্ষেত্রে ক্যানারি ডিপ্লয়মেন্ট কৌশল।
#     canary:         # ক্যানারি ডিপ্লয়মেন্ট কৌশল সংজ্ঞায়িত করে, যা ধাপে ধাপে নতুন সংস্করণে ট্র্যাফিক স্থানান্তর করে।
#       steps:        
#       - setWeight: 20     # প্রথম ধাপে, নতুন সংস্করণে 20% ট্র্যাফিক স্থানান্তর করা হবে।
#       - pause: {}                 # দ্বিতীয় ধাপে, একটি বিরতি থাকবে যা ডিফল্টভাবে 30 সেকেন্ডের জন্য স্থায়ী হবে, যা নতুন সংস্করণে ট্র্যাফিক স্থানান্তরের পরে পর্যবেক্ষণ করার জন্য ব্যবহৃত হয়।
#       - analysis:       # এই অংশটি বিশ্লেষণ সংজ্ঞায়িত করে, যা ক্যানারি ডিপ্লয়মেন্টের সময় নির্দিষ্ট করা হয় এবং যা নির্ধারণ করে যে ক্যানারি ডিপ্লয়মেন্ট সফল হয়েছে কিনা।
#           templates:    # এই অংশটি বিশ্লেষণ টেমপ্লেট সংজ্ঞায়িত করে, যা নির্ধারণ করে যে কোন বিশ্লেষণ টেমপ্লেট ব্যবহার করা হবে ক্যানারি ডিপ্লয়মেন্টের সময়।
#           - templateName: success-rate        # এই অংশটি নির্ধারণ করে যে "success-rate" নামের বিশ্লেষণ টেমপ্লেট ব্যবহার করা হবে ক্যানারি ডিপ্লয়মেন্টের সময়, যা পূর্বে সংজ্ঞায়িত করা হয়েছে এবং একটি ওয়েব হুক কল করে সফলতার হার পরিমাপ করে।
  
#       - setWeight: 40         # তৃতীয় ধাপে, নতুন সংস্করণে 40% ট্র্যাফিক স্থানান্তর করা হবে।
#       - pause:                # তৃতীয় ধাপের পরে, একটি বিরতি থাকবে যা 10 সেকেন্ডের জন্য স্থায়ী হবে, যা নতুন সংস্করণে ট্র্যাফিক স্থানান্তরের পরে পর্যবেক্ষণ করার জন্য ব্যবহৃত হয়।
#           duration: 10s       # চতুর্থ ধাপে, নতুন সংস্করণে 60% ট্র্যাফিক স্থানান্তর করা হবে।

#       - setWeight: 60
#       - pause:
#           duration: 20s

#       - setWeight: 80
#       - pause:
#           duration: 1m
#       - analysis:       # এই অংশটি বিশ্লেষণ সংজ্ঞায়িত করে, যা ক্যানারি ডিপ্লয়মেন্টের সময় নির্দিষ্ট করা হয় এবং যা নির্ধারণ করে যে ক্যানারি ডিপ্লয়মেন্ট সফল হয়েছে কিনা।
#           templates:    # এই অংশটি বিশ্লেষণ টেমপ্লেট সংজ্ঞায়িত করে, যা নির্ধারণ করে যে কোন বিশ্লেষণ টেমপ্লেট ব্যবহার করা হবে ক্যানারি ডিপ্লয়মেন্টের সময়।
#           - templateName: success-rate        # এই অংশটি নির্ধারণ করে যে "success-rate" নামের বিশ্লেষণ টেমপ্লেট ব্যবহার করা হবে ক্যানারি ডিপ্লয়মেন্টের সময়, যা পূর্বে সংজ্ঞায়িত করা হয়েছে এবং একটি ওয়েব হুক কল করে সফলতার হার পরিমাপ করে।

#   template:               # এই অংশটি পড টেমপ্লেট সংজ্ঞায়িত করে, যা নির্ধারণ করে যে রোলআউটের পডগুলি কেমন হবে।
#     metadata:             # এই অংশটি পডের মেটাডেটা সংজ্ঞায়িত করে, যেমন লেবেল ইত্যাদি। 
#       labels:             # এই অংশটি লেবেল সংজ্ঞায়িত করে, যা নির্ধারণ করে যে এই পডগুলিতে কোন লেবেল থাকবে।
#         app: rollouts-setweight     # এই লেবেলটি নির্ধারণ করে যে এই পডগুলিতে "app: rollouts-setweight" লেবেল থাকবে, যা রোলআউটের সিলেক্টর দ্বারা ব্যবহৃত হবে।
#     spec:               # এই অংশটি পডের স্পেসিফিকেশন সংজ্ঞায়িত করে, যা নির্ধারণ করে যে পডগুলি কেমন হবে, যেমন কোন কন্টেইনার থাকবে, কোন ইমেজ ব্যবহার করা হবে, কোন পোর্ট ব্যবহার করা হবে ইত্যাদি।
#       containers:       # এই অংশটি কন্টেইনার সংজ্ঞায়িত করে, যা নির্ধারণ করে যে পডগুলিতে কোন কন্টেইনার থাকবে, কোন ইমেজ ব্যবহার করা হবে, কোন পোর্ট ব্যবহার করা হবে ইত্যাদি।
#       - name: rollouts-setweight        # এই অংশটি কন্টেইনারের নাম সংজ্ঞায়িত করে, যা ইউনিক হতে হবে পডের মধ্যে।
#         image: nuruzzaman24x/canary     # এই অংশটি কন্টেইনার ইমেজ সংজ্ঞায়িত করে, যা নির্ধারণ করে যে পডগুলিতে কোন ইমেজ ব্যবহার করা হবে। এখানে "nuruzzaman24x/canary" ইমেজ ব্যবহার করা হচ্ছে, যা একটি ক্যানারি ডিপ্লয়মেন্টের জন্য তৈরি করা হয়েছে।
#         imagePullPolicy: Always         # এই অংশটি ইমেজ পুল পলিসি সংজ্ঞায়িত করে, যা নির্ধারণ করে যে কিভাবে কন্টেইনার ইমেজ পুল করা হবে। "Always" মানটি নির্দেশ করে যে কন্টেইনার ইমেজ প্রতিবার পড তৈরি বা রিস্টার্ট করার সময় পুল করা হবে, যা ডেভেলপমেন্ট বা টেস্টিং পরিবেশে সাধারণত ব্যবহৃত হয়।
#         env:
#         - name: html_name
#           # value: "app-v1.html"
#           value: "app-v3.html"
#         ports:
#         - containerPort: 5000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rollouts-setweight
# spec:
#   selector:
#     app: rollouts-setweight

#   ports:
#   - port: 5000
#     targetPort: 5000
#     protocol: TCP