apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-demo-application
  namespace: argocd
spec:
  destination:
    namespace: argo-events
    # namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: v17-combining-argo-tools/argo-rollouts
    repoURL: https://github.com/nuruzzaman24x/argocd-zeroto-hero-2ndpart.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
