# # First of all, use the below command to create docker-config-secret for pushing images to your private registry
# # kubectl create secret generic docker-config-secret --from-file=/path/to/.docker/config.json -n argo
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-push-wf-template

spec:
  templates:
    - name: build-and-push

      inputs:
        artifacts:
          - name: source
            path: /tmp/source

      volumes:
        - name: docker-config-secret
          secret:
            secretName: docker-config-secret

      container:
        image: moby/buildkit:v0.22.0

        command:
          - buildctl-daemonless.sh

        args:
          - build
          - --frontend
          - dockerfile.v0

          - --local
          - context=/tmp/source/v17-combining-argo-tools/app

          - --local
          - dockerfile=/tmp/source/v17-combining-argo-tools/app

          - --output
          - type=image,name={{workflow.parameters.nexus-registry}}/nginx:{{workflow.uid}},push=true,registry.insecure=true

        env:
          - name: DOCKER_CONFIG
            value: /.docker

        volumeMounts:
          - name: docker-config-secret
            mountPath: /.docker

        securityContext:
          privileged: true