apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    provider:
      job:
        metadata:
          labels:
            analysis: pre-promotion
        spec:
          backoffLimit: 0
          template:
            spec:
              restartPolicy: Never
              containers:
              - name: success-rate
                image: nuruzzaman24x/analysis:latest
                imagePullPolicy: Always
                command: ["/bin/bash", "-c"]
                args:
                  - ./app-success-rate.sh
                env:
                  - name: service_url
                    value: "http://rollout-bluegreen-preview.default.svc.cluster.local:5000"

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: blue-green-deployment

  strategy:
    blueGreen:
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: true

      prePromotionAnalysis:
        templates:
        - templateName: success-rate

  template:
    metadata:
      labels:
        app: blue-green-deployment
    spec:
      containers:
      - name: blue-green
        image: nuruzzaman24x/blue-green:latest
        imagePullPolicy: Always
        env:
        - name: html_name
          # value: "app-v1.html"
          value: "app-v2.html"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
spec:
  selector:
    app: blue-green-deployment
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
spec:
  selector:
    app: blue-green-deployment
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP