apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-traffic-management
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rollouts-traffic-management
  strategy:
    canary:
      # dynamicStableScale: true
      # abortScaleDownDelaySeconds: 20
      canaryService: canary-service
      stableService: stable-service
      steps:
      - setWeight: 20 # Using Setweight Only
      - pause: {}
      # ....................
      # - setCanaryScale: # Using SetCanaryScale with SetWeight
      #    weight: 40 
      # - setWeight: 40
      # - pause: {}
      trafficRouting:
        nginx:
          stableIngress: rollouts-traffic-management
  template:
    metadata:
      labels:
        app: rollouts-traffic-management
    spec:
      containers:
      - env:
        - name: html_name
          # value: "app-v1.html"
          value: "app-v2.html"
        image: nuruzzaman24x/canary
        name: rollouts-traffic-management
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: canary-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: rollouts-traffic-management
---
apiVersion: v1
kind: Service
metadata:
  name: stable-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: rollouts-traffic-management