apiVersion: argoproj.io/v1alpha1	#এটি Argo Rollouts CRD (Custom Resource Definition) ব্যবহার করছে।
kind: Rollout	#এটি Deployment এর বিকল্প, যেখানে Advanced Deployment Strategy ব্যবহার করা যায় (Blue-Green, Canary ইত্যাদি)।
metadata:
  name: rolling-update		# এই Rollout এর নাম "rolling-update
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rolling-update	#এই Rollout শুধুমাত্র "rolling-update" লেবেলযুক্ত Pods এর জন্য কাজ করবে।
  strategy:
    canary:			# এটি Canary Deployment ব্যবহার করবে
      maxSurge: 2		# replicas: 5 maxSurge: 2  Normal অবস্থায়: 5 pod, Update শুরু হলে Kubernetes সর্বোচ্চ:  5 + 2 = 7 pod  চালাতে পারবে।  এই অতিরিক্ত 2 pod-ই হলো surge pod। ধরো old version এর 5 pod চলছে।  নতুন version deploy করতে হবে।  যদি old pod আগে delete করো, তাহলে service interruption হতে পারে।  তাই Kubernetes আগে নতুন pod তৈরি করে:  Old = 5 New = 2 Total = 7  তারপর old pod ধীরে ধীরে remove করে।  Example ধরো:  replicas: 5 maxSurge: 2 শুরু Old = 5 New = 0 Total = 5 Update শুরু Old = 5 New = 2 Total = 7 কিছুক্ষণ পরে Old = 3 New = 2 Total = 5 শেষে Old = 0 New = 5 Total = 5
      maxUnavailable: 0	#  maxUnavailable: 2 হলো rollout/update চলার সময় সর্বোচ্চ কতগুলো Pod unavailable (service দিতে পারবে না) থাকতে পারবে তার limit।
  template:
    metadata:
      labels:
        app: rolling-update
    spec:
      containers:
      - env:
        - name: html_name
          # value: "app-v1.html"
          value: "app-v2.html"
        image: nuruzzaman24x/canary
        imagePullPolicy: IfNotPresent
        name: rolling-update
        ports:
        - containerPort: 5000
---
apiVersion: v1  # এটি Kubernetes-এর মূল API-এর v1 ভার্সন ব্যবহার করছে
kind: Service # এটি একটি Kubernetes Service, যা Pods-এর জন্য Load Balancing এবং Network Access নিশ্চিত করে।
metadata:
  name: rolling-update
spec:
  ports:
    - port: 5000    # এই সার্ভিসটি 5000 পোর্টে এক্সপোজ হবে (Cluster IP)।
      protocol: TCP
      targetPort: 5000  # Pod-এর ভেতরে চলমান অ্যাপ্লিকেশনও 5000 পোর্টে কাজ করবে।
  selector:
    app: rolling-update  # এই সার্ভিসটি শুধুমাত্র blue-green-deployment লেবেলযুক্ত Pods-এর জন্য কাজ করবে
  type: ClusterIP
