apiVersion: argoproj.io/v1alpha1    #এটি Argo Rollouts CRD (Custom Resource Definition) ব্যবহার করছে।
kind: Rollout   #এটি Deployment এর বিকল্প, যেখানে Advanced Deployment Strategy ব্যবহার করা যায় (Blue-Green, Canary ইত্যাদি)।
metadata:
  name: rollouts-setweight      # এই Rollout এর নাম "rolling-update
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rollouts-setweight   #এই Rollout শুধুমাত্র "rolling-update" লেবেলযুক্ত Pods এর জন্য কাজ করবে।
  strategy:
    canary:   #এটি Canary Deployment স্ট্রাটেজি ব্যবহার করবে, যেখানে নতুন ভার্সন ধীরে ধীরে প্রোডাকশনে পৌঁছাবে এবং সময়ের সাথে তার ট্রাফিক ও ভার্সন বাড়ানো হবে।     
      steps:       
      - setWeight: 20	# #নতুন version এ ২০% traffic যাবে, mane 1 ta pod  বাকি ৮০% পুরানো version এ থাকবে
      - pause: {}		#  এখানে কিছুক্ষণ থামবে → দেখে নেবে সব ঠিক আছে কিনা
      - setWeight: 40			# এখন ৪০% traffic নতুন version এ যাবে Pause: 10s  ১০ সেকেন্ড অপেক্ষা করবে
      - pause: {duration: 10s}
      - setWeight: 60			# এখন ৬০% traffic নতুন version এ যাবে Pause: 20s → ২০ সেকেন্ড অপেক্ষা করবে
      - pause: {duration: 20s}
      - setWeight: 80
      - pause: {duration: 1m}
  template:
    metadata:
      labels:
        app: rollouts-setweight
    spec:
      containers:
      - env:
        - name: html_name
          value: "app-v1.html"
          # value: "app-v2.html"
        image: nuruzzaman24x/canary
        imagePullPolicy: IfNotPresent
        name: rollouts-setweight
        ports:
        - containerPort: 5000
---
apiVersion: v1  # এটি Kubernetes-এর মূল API-এর v1 ভার্সন ব্যবহার করছে
kind: Service # এটি একটি Kubernetes Service, যা Pods-এর জন্য Load Balancing এবং Network Access নিশ্চিত করে।
metadata:
  name: rollouts-setweight
spec:
  ports:
  - port: 5000    # এই সার্ভিসটি 5000 পোর্টে এক্সপোজ হবে (Cluster IP)।
    protocol: TCP
    targetPort: 5000  # Pod-এর ভেতরে চলমান অ্যাপ্লিকেশনও 5000 পোর্টে কাজ করবে।
  selector:
    app: rollouts-setweight  # এই সার্ভিসটি শুধুমাত্র blue-green-deployment লেবেলযুক্ত Pods-এর জন্য কাজ করবে
  type: ClusterIP
