apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
  namespace: argo

rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor-default
  namespace: argo

subjects:
- kind: ServiceAccount
  name: default
  namespace: argo

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor
