# apiVersion: argoproj.io/v1alpha1
# kind: Workflow
# metadata:
#   generateName: argo-wf-  # Name of this Workflow
# spec:
#   arguments:
#     parameters:
#       - name: message
#         value: "Hello from spec.arguments" ## You can also comment out the value from here and pass it using "-p" when submitting the workflow, ex: argo submit templates.yml -p 'message="hello from terminal"' -n argo
#   entrypoint: dag-template # Defines "dag-template" as the "main" template
#   templates:
#   - name: dag-template # Defining the "dag template" as a Template Invocator, You must use one of "dag" or "steps" as a template invocator
#     dag:
#       tasks:
#         - name: A
#           template: container-template
#           arguments:
#             parameters:
#               - name: message
#                 value: "{{workflow.parameters.message}}"
#         - name: B
#           template: script-template
#           dependencies: [A]
#         - name: C
#           template: resource-template
#           dependencies: [A]
#         - name: D
#           template: delay-template
#           dependencies: [B, C]
# # - name: steps-template # Defining the "steps template" as a Template Invocator, You must use one of "dag" or "steps" as a template invocator
# #   steps:
# #   - - name: step1
# #       template: container-template
# #   - - name: step2a
# #       template: script-template
# #     - name: step2b
# #       template: resource-template
# #   - - name: step3
# #       template: delay-template


#   - name: container-template # Defining the "container template" as a Template Definition
#     inputs:
#       parameters:
#         - name: message
#     container:
#       image: alpine
#       command: ["/bin/sh", "-c"]
#       args: ["echo {{inputs.parameters.message}}"]
#   - name: script-template # Defining the "script template" as a Template Definition
#     script:
#       image: python:alpine3.6
#       command: [python]
#       source: |
#         import random
#         i = random.randint(1, 100)
#         print(i)
#   - name: resource-template # Defining the "resource template" as a Template Definition
#     resource:
#       action: create
#       manifest: |
#         apiVersion: v1
#         kind: ConfigMap
#         metadata:
#           generateName: argo-wf-resource-template-cm-
#         data:
#           created_by: argo-workflows
#   - name: delay-template # Defining the "delay template" as a Template Definition
#     suspend:
#       duration: "20s"





apiVersion: argoproj.io/v1alpha1      #Argo Workflows API version।  Kubernetes-কে বলছে:  "এই YAML টা Argo Workflow-এর resource।"
kind: Workflow                        #মানে:  "আমি একটা Workflow তৈরি করতে চাই।
metadata:
  generateName: argo-wf-  # Workflow-এর নাম।  Argo automatic suffix যোগ করবে।  উদাহরণ:  argo-wf-abcde argo-wf-x7h9k
spec:                     #Workflow-এর মূল configuration এখানে থাকে। Pod, Task, Template, Parameters সব spec এর ভিতরে define হয়।
  entrypoint: dag-template # Workflow start হবে কোন template থেকে।  মানে:  Main function = dag-template  Programming language-এর main() এর মতো।
  templates:               #Workflow-এর সব template-এর list। Template মানে reusable task definition।  উদাহরণ:  templates: - name: task1 - name: task2
  - name: dag-template    #একটা template define করা হচ্ছে।  নাম: dag-template, DAG = Directed Acyclic Graph  মানে task dependency define করবো।
    dag:                  #DAG = Directed Acyclic Graph। Task dependency management-এর জন্য ব্যবহার হয়।
      tasks:              #DAG-এর ভিতরে execute হওয়া task গুলোর list।
        - name: A         #Task A run করবে।  আর A ব্যবহার করবে:  container-template
          template: container-template      #এই task run করার সময় container-template, template ব্যবহার করো। Task নিজে কিছু execute করে না, template call করে।
        - name: B                         # A শেষ হওয়ার পরে B চলবে।
          template: script-template
          dependencies: [A]               #Task A complete না হওয়া পর্যন্ত এই task start হবে না।
        - name: C                         # C ও A-এর পরে চলবে।
          template: resource-template
          dependencies: [A]
        - name: D                         # D তখনই চলবে যখন: B AND C complete
          template: delay-template
          dependencies: [B, C]
  - name: container-template            # Container based task।
    inputs:                             # Template-এর input section। Parameter, Artifact ইত্যাদি receive করতে পারে।
      parameters:                       # User-defined variables। Runtime-এ value pass করা যায়।  উদাহরণ:  parameters: - name: username
        -  name: message                # Parameter name:  message
           value: "hello from inputs.parameters"    # Default value
    container:            #Container Template শুরু। Kubernetes Pod তৈরি হবে।
      image: alpine       #কোন Docker image ব্যবহার হবে।  এখানে:  Docker Hub → alpine:latest  Pull হবে।
      command: ["/bin/sh", "-c"]      #Container start হলে execute হবে:  /bin/sh -c
      args: ["echo {{inputs.parameters.message}}"]		#Command-এর argument।  এখানে:  args: - "echo {{inputs.parameters.message}}"  বাস্তবে execute হবে:  /bin/sh -c "echo hello from inputs.parameters"  Output:  hello from inputs.parameters
  - name: script-template # Defining the "script template" as a Template Definition
    script:                 #Script Template।  Argo automatically:  Pod create করবে Script file বানাবে Execute করবে
      image: python:alpine3.6     #Python runtime container।  এখানে Python pre-installed আছে।
      command: [python]           #Execute হবে:  python
      source: |                   #Script content।  | মানে multi-line string।  যা লিখবে সব Python script হিসেবে run হবে।
        import random             #Python random module import করছে।
        i = random.randint(1, 100)      #1 থেকে 100 পর্যন্ত random number generate করছে।
        print(i)                        #Random number log/output-এ দেখাবে।  উদাহরণ:  57
  - name: resource-template # Defining the "resource template" as a Template Definition
    resource:                 #Resource Template।  Kubernetes resource create/update/delete করতে ব্যবহৃত হয়।
      action: create          #Operation type।  Possible values:  create apply delete patch replace  এখানে:  ConfigMap create করবে।
      manifest: |             #যে Kubernetes resource create হবে তার YAML।
        apiVersion: v1
        kind: ConfigMap       #Kubernetes ConfigMap object।
        metadata:
          generateName: argo-wf-resource-template-cm-       #Kubernetes auto suffix যোগ করবে।  উদাহরণ:  argo-wf-resource-template-cm-x9d7k
        data:                                               #ConfigMap-এর key-value data section।
          created_by: argo-workflows                        #ConfigMap-এর ভিতরে store হওয়া data।
  - name: delay-template    # এখানে template-এর নাম delay-template।  অন্য কোনো task যখন এই template call করবে:  - name: D   template: delay-template  তখন delay-template execute হবে।
    suspend:                #suspend মানে:  Workflow-কে সাময়িকভাবে থামিয়ে (pause) রাখা।  এটা Container চালায় না, Script চালায় না, Pod-ও তৈরি করে না।  শুধু Argo Workflow-কে বলে:  "এখানে এসে একটু অপেক্ষা করো।
      duration: "20s"       #মানে:  ২০ সেকেন্ড Workflow pause থাকবে।  তারপর Argo automatically resume করবে।
